<?php

/**
 * @file 2
 * Module for Instagram API
 */

/**
 * Implements hook_menu().
 */
function a4s_instagram_menu() {
  $items = array();
  
  $items['insta'] = array(
    'title' => t('Instagram API'),
    'page callback' => 'a4s_instagram_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['behat'] = array(
    'title' => t('Behat test'),
    'page callback' => 'a4s_behat',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * 
 */
function a4s_behat() {
  /*
  $url = '';
  $ch = curl_init($url);
  curl_setopt($ch, CURLOPT_POST, TRUE);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  //curl_setopt($ch, CURLOPT_USERPWD, $username . ":" . $password);
  $results = json_decode(curl_exec($ch), TRUE);
  curl_close($ch);
  */
  watchdog('Request from Behat', '$_REQUEST ==> <pre>' . print_r($_REQUEST, TRUE) . '</pre>, $_SERVER ==> <pre>' . print_r($_SERVER, TRUE) . '</pre>');
  echo json_encode(array('status' => TRUE, '$_request' => $_REQUEST));
}

/**
 * 
 * @return string
 */
function  a4s_instagram_page() {
  
  $instagram_accounts_granted = variable_get('instagram_accounts_granted', NULL);
  if (!empty($instagram_accounts_granted) && !empty($instagram_accounts_granted['all4senses'])) {
    dpm($instagram_accounts_granted, '$instagram_accounts_granted');
    dpm('We have access. Let\'s Rock!');
   
    return 'Processed a real request to Instagram...';
  }
  
  dpm($_REQUEST, '$_REQUEST');
  $CLIENT_ID = '1eca294b0a6b478b9de165d9384edac1';
  $REDIRECT_URI = 'http://m-a-y.ru/insta';
  $CLIENT_SECRET = '59007de215f4492fb4cdca497e3b943a';
  
  if (!empty($_REQUEST['code'])) {
    $url = 'https://api.instagram.com/oauth/access_token';

    $data = array(
      'client_id' => $CLIENT_ID,
      'client_secret' => $CLIENT_SECRET,
      'grant_type' => 'authorization_code',
      'redirect_uri' => $REDIRECT_URI,
      'code'=> $_REQUEST['code'],
    ); 

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POST, count($data));
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

    $results = json_decode(curl_exec($ch), TRUE);
    curl_close($ch);
    dpm($results, '$results');
    if (!empty($results['access_token'])) {
      $instagram_accounts_granted[$results['user']['username']] = $results;
      variable_set('instagram_accounts_granted', $instagram_accounts_granted);
    }
    $out = 'We have got an access_token...';
    drupal_goto($REDIRECT_URI);
  }
  else {
     
    $out = '<a href="https://api.instagram.com/oauth/authorize/?client_id=' . $CLIENT_ID. '&redirect_uri=' . $REDIRECT_URI . '&response_type=code" >Authorize with Instagram</a>';
  }
  return $out;
}
